### PR TITLE
Fixes and updates

### LINKED ISSUE #318: Fix Metro and ferry icons and colors
Orange and light blue

### LINKED ISSUE #322: Time slider after last data is funny
https://drive.google.com/file/d/1VtBWcpiGeplRqE89-n1X-j6WEcIpHLNi/view 

https://dev-transitlog.hsldev.com/journey/20190513/072400/1083/2/0022_935?mapView=60.19068408617581%2C25.059814453125004%2C16&route.routeId=1083&route.direction=2&route.originStopId=1440101&journeyDetailsOpen=true&vehicle=0022%2F935&live=false&time=07%3A27%3A54&tab=vehicle-journeys&mapOverlays=Stop+radius&date=2019-05-13

### LINKED ISSUE #328: Time simulation not working, can't press the button

### PR DESCRIPTION
**Pull request by danieldunderfelt**
- Fix performance issue with alert icons on map.
- Add max limit for slider, make the time input follow the same rules (fixes #322)
- Fix the live toggle (fixes #328)
- Add colors and icons for subways and ferries (fixes #318)

### CODE REVIEW

File: src/components/sidepanel/ControlBar.js [hunk 1]
```diff
@@ -34,8 +34,10 @@ class ControlBar extends Component {
   onClickReset = () => {
     this.props.Filters.reset();
   };
+
   onClickUpdate = () => this.props.Update.update();
-  onToggleLive = () => this.props.Time2.toggleLive();
+
+  onToggleLive = () => this.props.Time.toggleLive();
```
Comment (danieldunderfelt) [inline src/components/sidepanel/ControlBar.js]: This was probably just an issue where the wrong window was focused and I typed in a "2" without noticing that anything had gone wrong.
