### PR TITLE
Fix timetable update

### LINKED ISSUE #207: Update did not really update
1. looking at the stop data in the morning
2. leave tab open to background, do everything else, including switching between wifi/lan
3. come back to using app, pressing update to get fresh data, nothing happens
4. F5 fixes

https://dev-transitlog.hsldev.com/?vehicle=&mapView=60.186851767280764%2C24.96119499206543%2C17&stop=1113131

### PR DESCRIPTION
**Pull request by danieldunderfelt**
Fixes #207. Set a fetchPolicy on the departure hfp query that should force it to ask the API for new data. Also fixes route stop markers not updating their style (border, color) when the data changes.

### CODE REVIEW

File: src/api.js [hunk 1]
```diff
@@ -53,6 +53,7 @@ export const getClient = async (UIStore) => {
   const dedupVehiclesLink = new ApolloLink((operation, forward) => {
     return forward(operation).map((data) => {
       if (data.data.vehicles.length > 5000) {
+        console.log("boop");
```
Comment (varpushaukka) [inline src/api.js]: o.O

Comment (danieldunderfelt) [reply src/api.js]: That's a very important part of the feature.
